### ISSUE TITLE
Commands not working (for me)

### ISSUE THREAD

**Issue by almai** [wp-cli/wp-super-cache-cli#12] opened 2016-11-02 15:59 UTC
I installed the plugin on the server and tried to execute the commands. But besides from `wp super-cache status` none of the them seems to work. I can't enable, disable, flush nor preload. When I enable or disable WP Super Cache by hand the status is always off.

![terminal_ _ssh_dahoam_ _240x58](https://cloud.githubusercontent.com/assets/402692/19936392/8828a3dc-a11d-11e6-9a6e-62e57f169e70.jpg)

**Comment by iandunn** [comment] 2016-11-04 17:21
I think this should be closed as a duplicate of #11

**Closed** 2016-11-04 17:45 UTC
